apiVersion: v1
kind: Service
metadata:
  name: gitops-demo
  namespace: gitops-demo
  labels:
    app: gitops-demo
spec:
  type: ClusterIP
  selector:
    app: gitops-demo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
